# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_teleop.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'robot_teleop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12robot_teleop.proto\x12\x05piper\">\n\x0bJointValues\x12\x0e\n\x06joints\x18\x01 \x03(\x02\x12\x0f\n\x07gripper\x18\x02 \x01(\x02\x12\x0e\n\x06\x65nable\x18\x03 \x01(\x08\"\x07\n\x05\x45mpty2B\n\x0cRobotService\x12\x32\n\x0eSendJointState\x12\x12.piper.JointValues\x1a\x0c.piper.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_teleop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTVALUES']._serialized_start=29
  _globals['_JOINTVALUES']._serialized_end=91
  _globals['_EMPTY']._serialized_start=93
  _globals['_EMPTY']._serialized_end=100
  _globals['_ROBOTSERVICE']._serialized_start=102
  _globals['_ROBOTSERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
